"""Subtitle file writers: SRT, WebVTT, ASS/SSA and plain text.

All writers share the exact same cue timing — only the container format
changes, so timing stays identical across formats by construction.
"""
from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Callable, List, Sequence

from ..utils.textproc import apply_rtl_marks, has_persian, wrap_lines
from .builder import Cue

TextGetter = Callable[[Cue], str]


@dataclass
class RenderOptions:
    max_chars_per_line: int = 42
    max_lines: int = 2
    rtl_marks: bool = True


def original_text(cue: Cue) -> str:
    return cue.text


def translated_text(cue: Cue) -> str:
    return cue.translation or cue.text


def _lines_for(cue: Cue, getter: TextGetter, opts: RenderOptions) -> List[str]:
    text = (getter(cue) or "").strip()
    lines = wrap_lines(text, max_len=opts.max_chars_per_line,
                       max_lines=opts.max_lines)
    if opts.rtl_marks and has_persian(text):
        lines = apply_rtl_marks(lines)
    return lines


# -- time formatting ---------------------------------------------------------

def _srt_time(t: float) -> str:
    t = max(0.0, t)
    ms = int(round(t * 1000))
    h, rem = divmod(ms, 3600000)
    m, rem = divmod(rem, 60000)
    s, ms = divmod(rem, 1000)
    return "%02d:%02d:%02d,%03d" % (h, m, s, ms)


def _vtt_time(t: float) -> str:
    return _srt_time(t).replace(",", ".")


def _ass_time(t: float) -> str:
    t = max(0.0, t)
    cs = int(round(t * 100))
    h, rem = divmod(cs, 360000)
    m, rem = divmod(rem, 6000)
    s, cs = divmod(rem, 100)
    return "%d:%02d:%02d.%02d" % (h, m, s, cs)


# -- writers ------------------------------------------------------------------

def write_srt(cues: Sequence[Cue], path: Path, getter: TextGetter,
              opts: RenderOptions) -> Path:
    blocks: List[str] = []
    for cue in cues:
        lines = _lines_for(cue, getter, opts)
        if not lines:
            continue
        blocks.append("%d\n%s --> %s\n%s" % (
            cue.index, _srt_time(cue.start), _srt_time(cue.end), "\n".join(lines)))
    path.write_text("\n\n".join(blocks) + "\n", encoding="utf-8-sig")
    return path


def write_vtt(cues: Sequence[Cue], path: Path, getter: TextGetter,
              opts: RenderOptions) -> Path:
    blocks: List[str] = ["WEBVTT", ""]
    for cue in cues:
        lines = _lines_for(cue, getter, opts)
        if not lines:
            continue
        blocks.append("%d\n%s --> %s\n%s\n" % (
            cue.index, _vtt_time(cue.start), _vtt_time(cue.end), "\n".join(lines)))
    path.write_text("\n".join(blocks), encoding="utf-8")
    return path


_ASS_HEADER = """[Script Info]
Title: Generated by Telegram Subtitle Bot
ScriptType: v4.00+
WrapStyle: 0
ScaledBorderAndShadow: yes
YCbCr Matrix: TV.709
PlayResX: 1280
PlayResY: 720

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,Vazirmatn,48,&H00FFFFFF,&H000000FF,&H00101010,&H64000000,0,0,0,0,100,100,0,0,1,2.2,0.8,2,60,60,40,178

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
"""


def write_ass(cues: Sequence[Cue], path: Path, getter: TextGetter,
              opts: RenderOptions) -> Path:
    events: List[str] = []
    for cue in cues:
        lines = _lines_for(cue, getter, opts)
        if not lines:
            continue
        text = "\\N".join(lines).replace("\n", "\\N")
        events.append("Dialogue: 0,%s,%s,Default,,0,0,0,,%s" % (
            _ass_time(cue.start), _ass_time(cue.end), text))
    path.write_text(_ASS_HEADER + "\n".join(events) + "\n", encoding="utf-8-sig")
    return path


def write_txt(cues: Sequence[Cue], path: Path, getter: TextGetter,
              opts: RenderOptions) -> Path:
    lines = [(getter(cue) or "").strip() for cue in cues]
    path.write_text("\n".join(l for l in lines if l) + "\n", encoding="utf-8")
    return path


_WRITERS = {
    "srt": write_srt,
    "vtt": write_vtt,
    "ass": write_ass,
    "ssa": write_ass,  # SSA consumers read v4+ fine in practice
    "txt": write_txt,
}


def write_outputs(cues: Sequence[Cue], out_dir: Path, base: str,
                  formats: Sequence[str], source_lang: str,
                  translated: bool, opts: RenderOptions) -> List[Path]:
    """Write requested formats.

    Persian (translated) files are produced in every requested format; the
    original-language transcript is always included as SRT for reference.
    """
    out_dir.mkdir(parents=True, exist_ok=True)
    written: List[Path] = []
    lang = (source_lang or "orig").lower()

    if translated:
        for fmt in formats:
            writer = _WRITERS.get(fmt)
            if not writer:
                continue
            written.append(writer(cues, out_dir / ("%s.fa.%s" % (base, fmt)),
                                  translated_text, opts))
        written.append(write_srt(cues, out_dir / ("%s.%s.srt" % (base, lang)),
                                 original_text, opts))
    else:
        for fmt in formats:
            writer = _WRITERS.get(fmt)
            if not writer:
                continue
            written.append(writer(cues, out_dir / ("%s.%s.%s" % (base, lang, fmt)),
                                  original_text, opts))
    return written
